presas_mx_dbt:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: "{{ env_var('DBT_WAREHOUSE_PATH', '../warehouse.duckdb') }}"
      threads: 4
      extensions:
        - httpfs
        - parquet
    prod:
      type: duckdb
      path: "{{ env_var('DBT_WAREHOUSE_PATH', '../warehouse.duckdb') }}"
      threads: 4